### ISSUE TITLE
Error: Cannot find module 'postcss-plugin-utilities'

### ISSUE THREAD

**Issue by Blindmikey** [arpadHegedus/postcss-font-vsize#1]
```
Error: Cannot find module 'postcss-plugin-utilities'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\node_modules\postcss-font-vsize\
index.js:10:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Any idea why this error message occurs when using postcss-font-vsize?

**Comment by blindmikey** [comment]
This looks like the package.json file for this repo does not include postcss-plugin-utilities as a dependency despite it being a dependency.

Not sure if it's a true dependency or a remnant of development?

**Comment by arpadHegedus** [comment]
Fixed with last commit. Thanks for reporting the issue. Update to latest version, or reinstall.
